name: Test Flask Website

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        python-version: ['3.9', '3.10', '3.11']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}
        cache: 'pip'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
        pip install -r test_requirements.txt
        pip install pytest-html
    
    - name: Run all tests with coverage
      run: |
        python -m pytest --cov=. --cov-report=xml --cov-report=html --html=report.html --self-contained-html -v
    
    - name: List generated files
      run: |
        echo "Generated files:"
        ls -la *.html *.xml || echo "No HTML/XML files found"
        ls -la htmlcov/ || echo "No htmlcov directory found"
    
    - name: Upload coverage to Codecov
      uses: codecov/codecov-action@v4
      if: always()
      with:
        file: ./coverage.xml
        flags: unittests
        name: codecov-umbrella
        fail_ci_if_error: false
    
    - name: Upload test results
      uses: actions/upload-artifact@v4
      if: always()
      with:
        name: test-results-python-${{ matrix.python-version }}
        path: |
          report.html
          htmlcov/
          coverage.xml
        if-no-files-found: warn
